name: aws-push-wedding | Push Wedding to Bucket

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  push-to-bucket:
    name: Push to Bucket on AWS
    runs-on: ubuntu-latest
    environment: aws-gg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.MAIN_REGION }}

      - name: Push to Bucket
        run: |
          aws s3 sync ./jmiiwedding.com ${{ vars.BUCKET_WEDDING }}/jmiiwedding.com --delete
          aws s3 sync ./w.ladicdn.com ${{ vars.BUCKET_WEDDING }}/w.ladicdn.com --delete
          aws s3 sync ./w.ladicdn.com_443 ${{ vars.BUCKET_WEDDING }}/w.ladicdn.com_443 --delete
          aws s3 sync ./cdn ${{ vars.BUCKET_WEDDING }}/cdn --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
          --paths "/*"
